#ifndef APP_OUTPUT
#define APP_OUTPUT

typedef enum
{
    APP_OUTPUT_SET_REF_ILLUMINANCE,
    APP_OUTPUT_SET_REF_AIR_TEMPERATURE,
    APP_OUTPUT_SET_REF_AIR_HUMIDITY,
    APP_OUTPUT_SET_REF_SOIL_MOISTURE,
    APP_OUTPUT_SET_ENABLE_ON_OFF,
    APP_OUTPUT_SET_ENABLE_PWM,
} APP_OUTPUT_SETTING_REF_TYPE_t;

void APP_OUTPUT_Init();
void APP_OUTPUT_SetRefValue(APP_OUTPUT_SETTING_REF_TYPE_t type, float value);

#endif
